import random
from pyrogram import filters
from pyrogram.types import Message
from AloneMusic import app

# Doğruluk soruları
dogruluk_listesi = [
    "Hiç kimseye söylemediğin bir sırrını paylaşır mısın?",
    "Şu an en çok utandığın anını anlatır mısın?",
    "Birine asla söylemem dediğin ama burada açıklayabileceğin bir şey var mı?",
    "Hiç birine yalan söyleyip sonradan pişman oldun mu?",
    "Hayatında en çok kime güveniyorsun?",
    "Şimdiye kadar yaptığın en büyük saçmalık neydi?",
    "Birine gizliden hoşlandığın oldu mu? Kimdi?",
    "Ailenden sakladığın en büyük sır nedir?",
    "Arkadaşlarına hiç ihanet ettin mi?",
    "Bir günlüğüne görünmez olsan ilk ne yapardın?",
    "Çocukken yaptığın en yaramazlık neydi?",
    "İlk aşkını hala hatırlıyor musun?",
    "Hiç sosyal medyada stalk yaptın mı?",
    "Sevdiğin birine yalan söyledin mi?",
    "Okulda başına gelen en komik olay neydi?",
    "Şu an en büyük hayalin nedir?",
    "Hiç kavga ettin mi? Sebebi neydi?",
    "Hoşlandığın kişiye açılıp reddedildin mi?",
    "Senden gizlenen bir şeyi öğrenmek istesen bu ne olurdu?",
    "Bir daha asla yapmam dediğin bir şey var mı?",
    # Ek 50 soru
    "Hiç büyük bir sırrı ortaya çıkarmak zorunda kaldın mı?",
    "En utanç verici anını anlatır mısın?",
    "Hiç aşık olduğun kişiyi kaybettin mi?",
    "Hayatında en çok pişman olduğun şey nedir?",
    "Hiç çaldığın bir şey oldu mu?",
    "En büyük korkun nedir?",
    "Bir arkadaşına zarar verdin mi?",
    "Hiç gizlice birine bakarken yakalandın mı?",
    "Hayatındaki en büyük başarın nedir?",
    "Hiç birine yanlışlıkla büyük bir yalan söyledin mi?",
    "En saçma rüyanda ne gördün?",
    "Kendinle ilgili utanç verici bir alışkanlığın var mı?",
    "Hiç birine aşık olup söylemedin mi?",
    "Hayatında kimsenin bilmediği bir hobin var mı?",
    "Hiç birini kıskandın mı?",
    "Şu an sana en çok üzüntü veren şey nedir?",
    "Hiç biri hakkında dedikodu yaptın mı?",
    "Hayatında en çok pişman olduğun karar nedir?",
    "Hiç birini gizlice takip ettin mi?",
    "En utanç verici mesajını paylaşabilir misin?",
    "Hiç kendini yanlış ifade ettin mi?",
    "En sevdiğin çocukluk oyuncağın neydi?",
    "Birine karşı yalan söylemek zorunda kaldın mı?",
    "Hiç birine gizlice yardım ettin mi?",
    "Hiç aşık olduğun kişiye reddedildin mi?",
    "En sevmediğin alışkanlığın nedir?",
    "Birine ihanet ettin mi?",
    "Hiç birine büyük bir sır verdin mi?",
    "Hayatında en çok gurur duyduğun an nedir?",
    "Hiç birine kırıcı bir şey söyledin mi?",
    "Hiç kimseye söylemediğin bir hayalini paylaşır mısın?",
    "En yakın arkadaşını kıskandın mı?",
    "Hiç biriyle kavga ettin mi?",
    "Birine ihanet ettiğini fark ettin mi?",
    "Hiç gizli bir yeteneğin var mı?",
    "En büyük başarısızlığın nedir?",
    "Birine kendini ifade edemediğin oldu mu?",
    "Hiç birini yanlış anladın mı?",
    "Hayatında en çok korktuğun an neydi?",
    "Hiç kimseye itiraf edemediğin bir duygun var mı?",
    "En büyük yalanın neydi?",
    "Hiç biri hakkında yanlış bir kanıya sahip oldun mu?",
    "En büyük sırrını kimle paylaşabilirsin?",
    "Hiç biri için ağladın mı?",
    "Hiç aşık olup karşılık bulamadın mı?",
    "Hiç biri hakkında gizlice düşündüğün bir şey var mı?",
    "Hayatında aldığın en zor karar neydi?",
    "En sevdiğin çocukluk anın nedir?",
    "Hiç biri için fedakarlık yaptın mı?",
    "En utanç verici alışkanlığın nedir?",
    "Hiç biri için pişmanlık duydun mu?",
    "Hayatında unutamadığın biri var mı?",
]

# Cesaret soruları
cesaret_listesi = [
    "Hemen şimdi en yakın arkadaşına 'Seni seviyorum' yaz ve ekran görüntüsünü paylaş!",
    "Grup içinde rastgele birine komik bir takma ad ver!",
    "Kendi hakkında utandırıcı bir gerçeği sesli mesajla söyle!",
    "Telefonundaki son mesajı burada paylaş!",
    "Birini arayıp ona şarkı söyle!",
    "Gruba en komik selfie’ni at!",
    "Şu an yanında olan bir nesnenin fotoğrafını çekip gönder!",
    "Bir arkadaşının profil fotoğrafını taklit et ve paylaş!",
    "Grup içinden rastgele birini öv!",
    "En sevmediğin yemeği itiraf et ve nedenini açıkla!",
    "Şimdi en yakın arkadaşına saçma bir emoji spamla!",
    "Son arama kaydını burada paylaş!",
    "Hiç konuşmadığın birine merhaba de!",
    "Grup içinden birinin adını ters söyle!",
    "Şimdi gözlerini kapatıp rastgele bir sticker gönder!",
    "Yanındaki kişiye seni tanımlayan üç kelime söylemesini iste!",
    "1 dakika boyunca sadece emojilerle konuş!",
    "Kendi telefonunda ilk gördüğün fotoğrafı paylaş!",
    "Grup içinden birine rastgele iltifat et!",
    "Şu an aklına gelen ilk şarkının nakaratını yaz!",
    # Ek 50 soru
    "Hemen şimdi grubun en sessiz üyesine şaka yap!",
    "Yanındaki kişiye en saçma şarkıyı söyle!",
    "Grubun en yaşlı üyesine emoji ile mesaj at!",
    "Telefonunda en son çektiğin fotoğrafı paylaş!",
    "Yanındaki kişiye en komik iltifatı yap!",
    "Birine 1 dakika boyunca sadece emoji ile cevap ver!",
    "Telefonundaki en eski fotoğrafı paylaş!",
    "Grup içinden rastgele birine şaka yap!",
    "Hemen şimdi komik bir dans yap ve kaydet!",
    "Grup içinde birine abartılı bir övgü yap!",
    "En garip sesini taklit et ve gönder!",
    "Grup sohbetinde rastgele bir şarkı yaz!",
    "Telefonundaki son videoyu paylaş!",
    "Yanındaki kişiye en saçma soruyu sor!",
    "Hemen bir arkadaşına tuhaf bir şaka yap!",
    "Birine saçma bir takma ad tak!",
    "Telefonunda en garip uygulamayı paylaş!",
    "Grup içinde rastgele birine iltifat et!",
    "Yanındaki kişiye rastgele emoji gönder!",
    "Birine taklit yap ve paylaş!",
    "Grup içinde rastgele birini etiketle ve komik bir şey yaz!",
    "Hemen kendini tanımlayan üç kelime söyle!",
    "Grup içinde 1 dakika boyunca sadece GIF gönder!",
    "Yanındaki kişiye şarkı söyle!",
    "Telefonunda en son dinlediğin şarkıyı paylaş!",
    "Grup sohbetinde rastgele birine mesaj at!",
    "Kendi sesini değiştirip mesaj at!",
    "Grup içinden birine abartılı iltifat yap!",
    "Telefonunda en son gönderdiğin sticker’ı paylaş!",
    "Yanındaki kişiye en saçma takma adı tak!",
    "1 dakika boyunca sadece komik sesler çıkar!",
    "Grup içinde rastgele birine komik emoji gönder!",
    "Bir arkadaşına gizli bir mesaj yaz!",
    "Telefonundaki en son aramayı paylaş!",
    "Hemen kendine en komik isim tak!",
    "Grup içinde rastgele birine şaka yap!",
    "Yanındaki kişiye rastgele bir hikaye anlat!",
    "Telefonunda en saçma fotoğrafı paylaş!",
    "Grup sohbetinde rastgele birine iltifat yaz!",
    "1 dakika boyunca sadece şarkı sözleri yaz!",
    "Bir arkadaşına en saçma emoji gönder!",
    "Yanındaki kişiye komik bir takma ad tak!",
    "Grup içinde rastgele birine şaka gönder!",
    "Telefonundaki son video kaydını paylaş!",
    "Hemen bir arkadaşına saçma bir ses gönder!",
    "Grup içinde rastgele birine komik bir takma ad ver!",
    "Yanındaki kişiye rastgele bir emoji gönder!",
    "1 dakika boyunca sadece komik mesajlar yaz!",
    "Telefonundaki en son selfie’yi paylaş!",
    "Grup içinden rastgele birine şaka yap!",
]

@app.on_message(filters.command(["d", "c"]))
async def dogruluk_cesaret(c: app, m: Message):
    command = m.command[0]

    if command == "d":
        return await m.reply_text(
            f"**✅ Doğruluk mu ? ?? Cesaret mi ?**\n\n"
            f"{m.from_user.mention} Doğruluk sorusu seçti !\n\n"
            f"{random.choice(dogruluk_listesi)}"
        )

    elif command == "c":
        return await m.reply_text(
            f"**✅ Doğruluk mu ? ?? Cesaret mi ?**\n\n"
            f"{m.from_user.mention} Cesaret sorusu seçti !\n\n"
            f"{random.choice(cesaret_listesi)}"
        )